# -*- coding: utf-8 -*-
"""biaya_parkir_18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-4-gXwgywo6RIZke160m9pxueFihMLuN
"""

jam_masuk = float(input("Masukkan jam masuk : "))
jam_keluar = float(input("Masukkan jam keluar : "))

durasi = jam_keluar - jam_masuk
if durasi <= 0:
    print("Durasi parkir tidak valid")

else:
    if durasi <= 2:
        biaya = 3000
    elif durasi > 2:
        sisa_jam = durasi - 2
        if sisa_jam > int(sisa_jam):
            sisa_jam = int(sisa_jam) + 1
        biaya = 3000 + (sisa_jam * 1000)

    print(f"Total biaya parkir: Rp {int(biaya)}.")