# -*- coding: utf-8 -*-
"""email_generator_62.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yXzcBASeJ4buhqkf6SrrAsCef3KgEhVC
"""

# Membuat email dari Nama dan NIM

nama_depan = input("Masukkan nama depan : ")
nim = input("Masukkan nim : ")

email = (f"{nama_depan}.{nim}@sekolah.ac.id").lower()

print(email)