# -*- coding: utf-8 -*-
"""kamus_sederhana_35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuR4PWLiw23ULcEpcPdL3LxDBy-E7AYO
"""

kamus = {"apel" : "apple", "kucing" : "cat", "ayam" : "chicken"}

kata_ind = input("Masukkan kata bahasa indonesia : ")

if kata_ind in kamus:
    terjemahan = kamus[kata_ind]
    print(f"Terjemahan dari {kata_ind} adalah {terjemahan}")

else:
    print("Terjemahan tidak ditemukan")