# -*- coding: utf-8 -*-
"""maxmin_list_34.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qe6HrTfQfxbERTv-mqwC-ZSBlf5xOFfm
"""

data = []

def maksimal():
    terbesar = data[0]
    for i in range(len(data)):
        if data[i] > terbesar:
            terbesar = data[i]
    return terbesar

def minimum():
    terkecil = data[0]
    for i in range(len(data)):
        if data[i] < terkecil:
            terkecil = data[i]
    return terkecil

for i in range(5):
    angka = int(input(f"Masukkan Angka ke-{i + 1} : "))
    data.append(angka)

angka_maksimal = maksimal()
angka_minimum = minimum()


print(f"Nilai Tertinggi: {angka_maksimal}, Terendah: {angka_minimum}")