# -*- coding: utf-8 -*-
"""Dictionary.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TkQb2JYdfKMGQ3REdbRydLLMe6VRHfE5
"""

data_buku = {

        "BOOK1" :   {"Judul" : "Biru",
                    "Penulis" : "Pak Biru",
                    "Tahun" : 2000},

        "BOOK2" :   {"Judul" : "Merah",
                    "Penulis" : "Merah Sinar",
                    "Tahun" : 1990},
}

def lihat_katalog():
    for key, value in data_buku.items():
        print()
        print(key)
        for key, value in value.items():
            print(f"{key} : {value}")

def tambah_buku():
    kode = input("Masukkan kode buku : ")
    judul = input("Masukkan judul buku : ")
    penulis = input("Masukkan nama penulis : ")
    tahun = input("Masukan tahun terbit : ")

    data_buku[kode] = {
        "Judul" : judul,
        "Penulis" : penulis,
        "Tahun" : tahun
    }

    print(f"Buku judul {judul} sudah berhasil di tambahkan")

def cari_buku():
    cari_judul = input("Masukkan judul buku : ")
    found = False
    for kode_buku, info_buku in data_buku.items():
        if cari_judul in info_buku["Judul"]:
            print(f"\nBuku ditemukan untuk judul '{cari_judul}':")
            print(f"Kode Buku : {kode_buku}")
            for key, value in info_buku.items():
                print(f"{key} : {value}")
            found = True
            break
    if not found:
        print(f"Buku dengan judul '{cari_judul}' tidak ditemukan.")

def print_menu():
    print("=== PERPUSTAKAAN ===")
    print("1. Lihat Katalog")
    print("2. Tambah Buku")
    print("3. Cari Buku")
    print("0. Keluar")

while True:
    print()
    print_menu()
    print()
    menu = input("Masukkan pilihan menu : ")
    if menu == "1":
        lihat_katalog()
        input("\nEnter untuk kembali")
    elif menu == "2":
        tambah_buku()
        input("\nEnter untuk kembali")
    elif menu == "3":
        cari_buku()
        input("\nEnter untuk kembali")
    else:
        break