# -*- coding: utf-8 -*-
"""list.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IwcTXzHv2bdzeR9UlryCB_icP8nNu3Cv
"""

keranjang = ["Pensil", "Ballpoint", "Spidol", "Pensil"]

def lihat_keranjang():
    if len(keranjang) == 0:
        print("Keranjang masih kosong")
    else:
        for barang in keranjang:
            print(barang)

def tambah_barang():
    barang_baru = input("Masukkan barang : ")
    keranjang.append(barang_baru)
    print(f"{barang_baru} berhasil ditambahkan")

def update_barang():
    masukan = input("barang yang akan diganti : ")

    for i in range(len(keranjang)):
        if keranjang[i] == masukan:
            masukan_baru = input("Update nama barang : ")
            keranjang[i] = masukan_baru
            print("Berhasil update")
            return keranjang
            break
        else:
            print("Barang tidak valid")

def hapus_barang():
    masukan = input("barang yang akan dihapus : ")

    for barang in keranjang:
        if barang == masukan:
            keranjang.remove(barang)
            print(f"{masukan} Berhasil dihapus")
            break
        else:
            print("Barang tidak valid")

def menu():
    print()
    print("== TOKO ONLINE ==")
    print("1. Lihat Barang")
    print("2. Update Barang")
    print("3. Tambah Barang")
    print("4. Hapus Barang")
    print("5. Keluar")
    print()

while True:
    menu()

    pilihan_menu = int(input("Masukkan pilihan menu [1-5] : "))

    if pilihan_menu == 1:
        lihat_keranjang()
        input("Enter untuk kembali ke menu")

    elif pilihan_menu == 2:
        update_barang()
        input("Enter untuk kembali ke menu")

    elif pilihan_menu == 3:
        tambah_barang()
        input("Enter untuk kembali ke menu")

    elif pilihan_menu == 4:
        hapus_barang()
        input("Enter untuk kembali ke menu")

    elif pilihan_menu == 5:
        print("Keluar dari program")
        break

    else:
        pri

