# -*- coding: utf-8 -*-
"""set.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O09e9snD5ekD6HUGQscUI7QJhA2stp-j
"""

daftar_buah = {"apel", "jagung"}

def lihat_jenis():
    for buah in daftar_buah:
        print(buah)

def tambah_jenis():
    jenis_baru = input("Masukkan jenis buah yang akan ditambahkan : ")
    for i in daftar_buah:
        if i == jenis_baru:
            print(f"{jenis_baru} sudah ada di dalam daftar")
            break
    daftar_buah.add(jenis_baru)
    print(f"{jenis_baru} berhasil ditambahkan")

def hapus_jenis():
    jenis = input("Masukkan jenis buah yang akan dihapus : ")
    if jenis not in daftar_buah:
        print(f"{jenis} tidak ada didalam daftar")
    else:
        daftar_buah.discard(jenis)
        print(f"{jenis} berhasil dihapus")

def cek_jenis():
    jenis = input("Masukkan jenis buah yang akan di cari : ")

    if jenis in daftar_buah:
        print(f"{jenis} ada di dalam daftar")
    else:
        print(f"{jenis} tidak ada di daftar")

print("1. Lihat Jenis")
print("2. Cek Jenis")
print("3. Tambah Buah")
print("4. Hapus Buah")
print("5. Keluar")

while True:
    pilihan = int(input("Masukkan pilihan : "))

    if pilihan == 1:
        lihat_jenis()
    elif pilihan == 2:
        cek_jenis()
    elif pilihan == 3:
        tambah_jenis()
    elif pilihan == 4:
        hapus_jenis()
    elif pilihan == 5:
        break
    else:
        print("pilihan tidak valid")