# -*- coding: utf-8 -*-
"""tuple.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-JJXrHMgDGHvNT4ivfGoAOzLctb7A4v-
"""

data_siswa = ("1", "1", 80, 80, 80)
nilai_mtk = data_siswa[2]
nilai_inf = data_siswa[3]
nilai_ipa = data_siswa[4]

def login():
    nama = input("Masukkan nama : ")
    password = input("Masukkan password : ")

    if nama == data_siswa[0] and password == data_siswa[1]:
        return True
    else:
        return False

def lihat_nilai():
    print(f"Nilai Matematika : {nilai_mtk}")
    print(f"Nilai Informatika : {nilai_inf}")
    print(f"Nilai IPA : {nilai_ipa}")

def rata_rata():
    total = 0
    for i in range(2, len(data_siswa)):
        total += data_siswa[i]

    rata_nilai = total / (len(data_siswa) - 2)
    return rata_nilai

def beranda():
    print()
    print("=== BERANDA ===")
    print("1. Login")
    print("0. Keluar")

def menu_user():
    print()
    print("=== CEK NILAI ===")
    print("1. Lihat Nilai")
    print("2. Lihat Rata-rata Nilai")
    print("0. keluar")

while True:
    beranda()
    pilihan = int(input("Masukkan pilihan : "))
    if pilihan == 1:
        if login():
            while True:
                menu_user()
                pilihan_menu = int(input("Masukkan pilihan menu : "))

                if pilihan_menu == 1:
                    lihat_nilai()
                    input("Enter untuk kembali")
                elif pilihan_menu == 2:
                    rata_nilai = rata_rata()
                    print(f"Rata rata nilai adalah : {rata_nilai}")
                    input("Enter untuk kembali")
                else:
                    break

        else:
            print("Login gagal")

    else:
        break